---
- name: Install python3 if necessary
  hosts: pi_zero
  remote_user: pi
  become: yes

  tasks:
   - name: Install python3
     apt:
       name: python3
       state: present
       update_cache: yes
