---
- name: Restart SSH Service
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: yes
  listen: sshd_restart
- name: Generate Locales
  command: /usr/sbin/locale-gen
  become: yes
  listen: "locale configuration change"
- name: Reboot
  listen: reboot
  reboot:
  become: yes
- name: Restart sudo service
  listen: sudo_reload
  service:
    name: sudo
    state: reloaded
  become: yes
